[tool.poetry]
package-mode = false # if this isn't a library for sharing.

# keep sorted with `poetry self add poetry-plugin-sort`.
[tool.poetry.dependencies]
python = "~3.14.6"

[tool.poetry.group.dev.dependencies]
fawltydeps = "~0.19.0"
pychoir = "~0.0.30"
pytest = "~8.2.1"
pytest-cov = "~5.0.0"
pytest-timeout = "~2.3.1"
pytest-xdist = "~3.6.1"
ruff = "~0.16.0"
qmock = "~1.0.0"

[tool.ruff.lint]
extend-select = [
    "ISC", # flake8-implicit-str-concat
    "N", # pep8-naming
    "TID252", # relative-imports
    "RUF102", # invalid-rule-code
    "RUF103", # invalid-suppression-comment
    "RUF104", # unmatched-suppression-comment
    "RUF105", # noqa-comments
    "RUF106", # rule-codes-in-suppression-comments # TODO: in preview as of 0.16.0
    # TODO: more.
]
ignore = [
    # There is nothing wrong with using `dict()`/`list()`/`tuple()` instead of
    # `{}`/`[]`/`()`. Names are more explicit and saving one builtin function call
    # has no practical performance benefit.
    "C408", # unnecessary-collection-call
    # Use f-strings everywhere by default. Unless there is *very heavy* logging,
    # deferring the formatting of logs just makes the strings harder to read for no
    # practical performance benefit.
    "G004", # logging-f-string
    # An explicit `else` after a jump (return, raise, continue, break) is not bad.
    # The matching nesting can often read better, even if it isn't strictly necessary.
    "RET505", # "superfluous-else-return"
    "RET506", # "superfluous-else-raise"
    "RET507", # "superfluous-else-continue"
    "RET508", # "superfluous-else-break"
    # Iterating over `dict.keys()` is more explicit than iterating over the `dict`
    # itself. There's no reason to discourage that.
    "SIM118", # in-dict-keys
    # If you use `.format()` (which you shouldn't), then use explicit placeholders.
    "UP030", # format-literals
]

[tool.ruff.lint.isort]
# Module-scope stuff is separated by 2 lines. Why not imports too.
lines-after-imports = 2
# Every `import` line imports only one thing; every imported thing gets its
# own `import` line.
force-single-line = true
# Enabling this really means "don't group by syntax", ie: don't group
# `import x` lines above `from x import y` lines; just sort by module names.
force-sort-within-sections = true
# "type" just means "naming convention". So disabling this means "don't
# group by naming convention", ie: don't group `ALL_CAPS`, `CamelCase`, and
# `snake_case` separately. Just sort alphabetically.
order-by-type = false

[tool.ruff.lint.pep8-naming]
extend-ignore-names = [
    "Test[A-Z_]*"
]

[tool.fawltydeps]
ignore_unused = [
    ### prod dependencies
    # ... any production pins for indirect deps or plugins used implicitly.
    ### dev dependencies
    "fawltydeps", # self
    "pytest-cov", # pytest plugin
    "pytest-timeout", # pytest plugin
    "pytest-xdist", # pytest plugin
    "ruff", # cli
    ### false positives from shared module names (https://github.com/tweag/FawltyDeps/issues/419)
    # ... any dependencies with module names that overlap with local project modules.
]

[tool.coverage.run]
source = ["src/"]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
testpaths = ["tests/"]
pythonpath = ["src/"]
filterwarnings = []
timeout = 5  # seconds
